openapi: 3.1.0
info:
  title: "COMP2001 API"
  summary: "This is a simple API doc using OpenAPI v3.1.0"
  description: "My simple python/sql server API documentation"
  version: 1.0.0
  contact:
    name: "Bobby Mannino"
    email: "manninobobby@icloud.com"
    url: "https://bobman.dev"
servers:
  - url: "http://cent-5-534.uopnet.plymouth.ac.uk/COMP2001/BMannino"
paths:
  "/trails":
    get:
      tags: ["trails"]
      operationId: "listTrails"
      summary: "Return an array of trails"
      description: "Returns all the trails. If the user is an admin will return all details, if not it will return limited details"
      parameters:
        - schema:
          "$ref": "#/components/parameters/limit"
        - schema:
          "$ref": "#/components/parameters/email"
        - schema:
          "$ref": "#/components/parameters/password"
      responses:
        "200":
          description: "An array of trails"
          content:
            "application/json":
              oneOf:
                - schema:
                  "$ref": "#/components/schemas/Trails"
    post:
      tags: ["trails"]
      operationId: "createTrail"
      summary: "Create a new trail"
      description: "Create a new trail in the database"
      parameters:
        - schema:
          "$ref": "#/components/parameters/email"
        - schema:
          "$ref": "#/components/parameters/password"
      responses:
        "201":
          description: "Created trail successfully"
  "/trails/{trailId}":
    get:
      tags: ["trails"]
      operationId: "trailInfo"
      summary: "Return info about a certain trail"
      description: "Returns info about a certain trail, if you are not an admin you will only get limited details"
      parameters:
        - schema:
          $ref: "#/components/parameters/trailId"
        - schema:
          "$ref": "#/components/parameters/email"
        - schema:
          "$ref": "#/components/parameters/password"
      responses:
        "200":
          description: "Information about a trail"
          content:
            "application/json":
              oneOf:
                - schema:
                  "$ref": "#/components/schemas/Trail"
    put:
      tags: ["trails"]
      operationId: "updateTrail"
      summary: "Update a trails information"
      description: "Update information about a trail in the database"
      parameters:
        - schema:
          $ref: "#/components/parameters/trailId"
        - schema:
          "$ref": "#/components/parameters/email"
        - schema:
          "$ref": "#/components/parameters/password"
      responses:
        "200":
          description: "Trail has been updated"
    delete:
      tags: ["trails"]
      operationId: "removeTrail"
      summary: "Remove a trail"
      description: "Remove a trail from the database"
      parameters:
        - schema:
          $ref: "#/components/parameters/trailId"
        - schema:
          "$ref": "#/components/parameters/email"
        - schema:
          "$ref": "#/components/parameters/password"
      responses:
        "204":
          description: "Trail has been removed"
components:
  schemas:
    TrailD1:
      type: "object"
      proporties:
        id:
          type: "integer"
          format: "int32"
        title:
          type: "string"
          format: "string"
        description:
          type: "string"
          format: "string"
    TrailsD1:
      type: "array"
      items:
        $ref: "#/components/schemas/TrailD1"
  parameters:
    trailId:
      name: "trailId"
      in: "path"
      required: true
      description: "The id of the trail"
      schema:
        type: "integer"
        format: "int32"
    email:
      name: "x-email"
      in: "header"
      required: false
      description: "The email of the user"
      schema:
        type: "string"
        format: "string"
    password:
      name: "x-password"
      in: "header"
      required: false
      description: "The password of the user"
      schema:
        type: "string"
        format: "password"
    limit:
      name: "limit"
      in: "query"
      description: "number of items to take"
      required: false
      schema:
        type: "integer"
        format: "int32"
tags:
  - name: "trails"
    description: "Trail (hike) operations"
